/**
 * The shape of the database, as the fake client needs to know it.
 *
 * TEST-ONLY. Nothing here is exported from the package index and nothing outside a test
 * imports it. It exists so Phase 9 can exercise the real repository → domain → API path
 * without a live Supabase project (PROGRESS.md Phase 9).
 *
 * This is a hand-written mirror of `supabase/migrations/`, and `schema-drift.test.ts`
 * fails if the two stop agreeing — a new migration that adds a table, a unique
 * constraint or a cascade has to be reflected here, or the suite goes red. A fake that
 * is allowed to drift from the migrations tests nothing.
 */

export interface UniqueConstraint {
  /** Constraint name, echoed in the 23505 error the way Postgres would. */
  name: string;
  columns: string[];
  /**
   * A partial unique index (migration 0007's `where effective_to is null`). Rows the
   * predicate rejects are not covered by the constraint.
   */
  where?: (row: Record<string, unknown>) => boolean;
}

export interface TableSchema {
  /** Columns generated by the database: id, created_at, updated_at. */
  generated: ('id' | 'created_at' | 'updated_at')[];
  /** Column defaults applied when an insert omits the column. */
  defaults?: Record<string, unknown>;
  /**
   * `numeric` columns. PostgREST returns numeric as a string, and the repositories are
   * typed for that, so the fake stores them the same way — otherwise a test would pass
   * against a number that production never sees.
   */
  numericColumns?: string[];
  uniques?: UniqueConstraint[];
  /**
   * `user_id references public.users (id) on delete cascade`. Deleting the user row
   * removes these rows too, which is the whole mechanism account deletion relies on
   * (privacy-service.ts).
   */
  cascadeOnUserDelete?: boolean;
  /** Append-only tables reject update and delete, matching their RLS policies. */
  appendOnly?: boolean;
}

export const SCHEMA: Record<string, TableSchema> = {
  users: {
    generated: ['id', 'created_at', 'updated_at'],
    defaults: {
      email: null,
      display_name: null,
      timezone: 'Asia/Kolkata',
      preferred_language: 'en',
    },
    uniques: [{ name: 'users_firebase_uid_key', columns: ['firebase_uid'] }],
  },

  commitments: {
    generated: ['id', 'created_at', 'updated_at'],
    defaults: {
      description: null,
      due_date: null,
      due_time: null,
      recurrence_rule: null,
      lead_days: null,
      status: 'pending',
      priority: 'normal',
    },
    cascadeOnUserDelete: true,
  },

  financial_obligations: {
    generated: ['id', 'created_at', 'updated_at'],
    numericColumns: ['amount'],
    defaults: { currency: 'INR', recurrence_rule: 'monthly' },
    cascadeOnUserDelete: true,
  },

  financial_instances: {
    generated: ['id', 'created_at', 'updated_at'],
    numericColumns: ['expected_amount', 'paid_amount'],
    defaults: { paid_amount: null, status: 'pending', paid_date: null },
    // finance-rules.md § Instance generation: this constraint, not a read-then-write
    // pre-check, is what makes instance generation idempotent under concurrency.
    uniques: [
      { name: 'financial_instances_obligation_id_period_key', columns: ['obligation_id', 'period'] },
    ],
    cascadeOnUserDelete: true,
  },

  memories: {
    generated: ['id', 'created_at', 'updated_at'],
    numericColumns: ['confidence'],
    defaults: { confidence: '1', effective_to: null },
    // Migration 0007's partial unique index: at most one *current* row per key.
    uniques: [
      {
        name: 'memories_current_key_uniq',
        columns: ['user_id', 'memory_type', 'key'],
        where: (row) => row.effective_to === null || row.effective_to === undefined,
      },
    ],
    cascadeOnUserDelete: true,
  },

  conversations: {
    generated: ['id', 'created_at', 'updated_at'],
    defaults: { title: null },
    cascadeOnUserDelete: true,
  },

  messages: {
    generated: ['id', 'created_at'],
    defaults: { language: null, intent: null },
    cascadeOnUserDelete: true,
  },

  ai_usage_events: {
    generated: ['id', 'created_at'],
    numericColumns: ['estimated_cost_usd'],
    defaults: { intent: null, estimated_cost_usd: null },
    cascadeOnUserDelete: true,
    appendOnly: true,
  },

  notifications: {
    generated: ['id', 'created_at', 'updated_at'],
    defaults: {
      commitment_id: null,
      instance_id: null,
      status: 'pending',
      read_at: null,
    },
    uniques: [{ name: 'notifications_dedupe_uniq', columns: ['user_id', 'dedupe_key'] }],
    cascadeOnUserDelete: true,
  },
};

export type TableName = keyof typeof SCHEMA;
